workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: YFSkey

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.youngfashionshow.staff

      vars:
        BUNDLE_ID: "com.youngfashionshow.staff"
        APP_STORE_APPLE_ID: "6072339384"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$CM_EXPORT_OPTIONS_PLIST

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true