workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: YFSkey

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect

      vars:
        BUNDLE_ID: "com.youngfashionshow.staff"
        APP_STORE_APPLE_ID: "6072339384"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true